
version: '2'
services:

  mysql.nginx:
    build: ./nginx/
    image: mysql.nginx:0.0.1
    container_name: mysql.nginx
    #hostname: mysql.nginx
    networks:
        - vlan
    #network_mode: "host"
    depends_on:
        - mysql.php.fpm
    volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf/conf.d:/etc/nginx/conf.d
        - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ./www:/www
        - ./logs:/var/log/nginx
        - "phpsocket:/var/run"
        - /var/opt:/var/opt
    restart: always
    ports:
        - 13306:13306

  mysql.php.fpm:
    build: ./php-fpm73/
    image: mysql.php.fpm:0.0.1
    container_name: mysql.php.fpm
    #hostname: mysql.php.fpm
    networks:
        - vlan
    #network_mode: "host"
    volumes:
        - ./php-fpm73/conf:/usr/local/etc/php-fpm.d
        - ./php-fpm73/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./www:/www
        - "phpsocket:/var/run"
    restart: always

  mysql:
    build: ./mysql_db/
    image: mysql:0.0.1
    container_name: mysql
    #hostname: mysql
    networks:
        - vlan
    #network_mode: "host"
    volumes:
        - ./mysql_db/data:/var/lib/mysql
        - ./mysql_db/conf/my.cnf:/etc/mysql/my.cnf
    environment:
       MYSQL_ROOT_PASSWORD: 1qasde32
    restart: always 
    ports:
        - 3306:3306

networks:
  vlan:

volumes:
  phpsocket:
